/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Dao.userDao;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author chabd
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form SignupForm
     */
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNoPattern = "^[0-9]*$";

    public SignupForm() {
        initComponents();
        SaveBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jTextField_phnNmbr = new javax.swing.JTextField();
        jTextField_adrs = new javax.swing.JTextField();
        jTextField_question = new javax.swing.JTextField();
        jTextField_answer = new javax.swing.JTextField();
        jPasswordField_paswrd = new javax.swing.JPasswordField();
        SaveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        forgotPswrdBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Name");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 173, 198, 25));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Password");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 274, 198, 25));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Mobile Number");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 326, 198, 25));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Email");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 220, 198, 25));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel7.setText("Address");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 382, 113, 25));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel8.setText("Answer");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 487, 198, 25));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel9.setText("Security Question");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 436, 198, 25));

        jTextField_name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 173, 416, -1));

        jTextField_email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_email.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_emailKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 220, 416, -1));

        jTextField_phnNmbr.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_phnNmbr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField_phnNmbr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_phnNmbrKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_phnNmbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 326, 416, -1));

        jTextField_adrs.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_adrs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField_adrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_adrsKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_adrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 382, 416, -1));

        jTextField_question.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_question.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_questionActionPerformed(evt);
            }
        });
        jTextField_question.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_questionKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 436, 416, -1));

        jTextField_answer.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField_answer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField_answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_answerKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 487, 416, -1));

        jPasswordField_paswrd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPasswordField_paswrd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPasswordField_paswrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_paswrdKeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordField_paswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 274, 416, -1));

        SaveBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\chabd\\OneDrive\\Documents\\Cafe Image & Icon\\images\\save.png")); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 537, 110, 40));

        clearBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\chabd\\OneDrive\\Documents\\Cafe Image & Icon\\images\\clear.png")); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 537, 110, 40));

        exitBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\chabd\\OneDrive\\Documents\\Cafe Image & Icon\\images\\exit small.png")); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 536, 100, 43));
        exitBtn.getAccessibleContext().setAccessibleDescription("");

        forgotPswrdBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        forgotPswrdBtn.setText("Forgot Password");
        forgotPswrdBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        forgotPswrdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPswrdBtnActionPerformed(evt);
            }
        });
        getContentPane().add(forgotPswrdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 600, 180, 40));

        loginBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\chabd\\OneDrive\\Documents\\Cafe Image & Icon\\images\\login.png")); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 600, 103, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Sign Up");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 189, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\chabd\\OneDrive\\Documents\\Cafe Image & Icon\\images\\first page background.PNG")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void clear() {

        jTextField_name.setText("");
        jTextField_email.setText("");
        jPasswordField_paswrd.setText("");
        jTextField_phnNmbr.setText("");
        jTextField_adrs.setText("");
        jTextField_question.setText("");
        jTextField_answer.setText("");
        SaveBtn.setEnabled(false);

    }

    public void validateFields() {
        String name = jTextField_name.getText();
        String email = jTextField_email.getText();
        String address = jTextField_adrs.getText();
        String mobileNumber = jTextField_phnNmbr.getText();
        String password = String.valueOf(jPasswordField_paswrd.getPassword());
        String securityQuestion = jTextField_question.getText();
        String answer = jTextField_answer.getText();

        if (!name.equals("") && email.matches(emailPattern) && mobileNumber.matches(mobileNoPattern) && mobileNumber.length() == 11 && !address.equals("") && !password.equals("") && !securityQuestion.equals("") && !answer.equals("")) {
            SaveBtn.setEnabled(true);
        } else {
            SaveBtn.setEnabled(false);
        }
    }
    private void jTextField_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_questionActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // Save Button code here:
        User user = new User();
        user.setName(jTextField_name.getText());
        user.setEmail(jTextField_email.getText());
        user.setAddress(jTextField_adrs.getText());
        user.setMobileNumber(jTextField_phnNmbr.getText());
        user.setPassword(String.valueOf(jPasswordField_paswrd.getPassword()));
        user.setSecurityQuestion(jTextField_question.getText());
        user.setAnswer(jTextField_answer.getText());
        userDao.save(user);
        clear();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // Exit Button code here:
        int isExit = JOptionPane.showConfirmDialog(null, "Do you want to exit", "Select", JOptionPane.YES_NO_OPTION);
        if (isExit == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clear();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void jTextField_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_nameKeyReleased

    private void jTextField_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_emailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_emailKeyReleased

    private void jPasswordField_paswrdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_paswrdKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jPasswordField_paswrdKeyReleased

    private void jTextField_phnNmbrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phnNmbrKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_phnNmbrKeyReleased

    private void jTextField_adrsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_adrsKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_adrsKeyReleased

    private void jTextField_questionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_questionKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_questionKeyReleased

    private void jTextField_answerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_answerKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_answerKeyReleased

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void forgotPswrdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPswrdBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_forgotPswrdBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton forgotPswrdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField_paswrd;
    private javax.swing.JTextField jTextField_adrs;
    private javax.swing.JTextField jTextField_answer;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_phnNmbr;
    private javax.swing.JTextField jTextField_question;
    private javax.swing.JButton loginBtn;
    // End of variables declaration//GEN-END:variables
}
